### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by jodrell2000** [jodrell2000/DaManagement#131]
Should I type /bow or /bows ?? Why not either!

**Comment by 1hitsong** [comment]
1. Aliases should be stored in node-storage or Db so they can be added / removed / edited by commands without updating them in code
2. Possible storage layout: `aliases:[{
command: `/dice {1} {2}`,
alias: `/roll {1} {2}`
}]`
3. 1st we check if a chat message is a command. If not, we then check all aliases. If alias is found we then call the corresponding command with the arguments passed
4. Alias check should be for the string in total or substring up to the first `{` char. This allows aliases to have spaces and still correctly pass arguments
5. Create admin command to add new aliases.` /addalias /roll {1} {2} /dice {1} {2}` -> calling /roll will now call /dice
6. Create admin command to edit aliases.` /editalias /roll {1} {2} /rolldice {1} {2}` -> alias is now /rolldice instead of /roll
7. Create admin command to remove aliases.` /removealias /roll {1} {2}` -> Alias is removed

**Comment by 1hitsong** [comment]
For now I removed allowing spaces in the command. This removes the need for the arguments on the alias and greatly simplifies the code. We can come back to it in the future if wanted.
