### ISSUE TITLE
Sometimes the stats post in chat is out of order

### ISSUE THREAD

**Issue by 1hitsong** [jodrell2000/DaManagement#158]
![Screenshot from 2022-01-25 07-55-33](https://user-images.githubusercontent.com/3330318/150980884-769cba8c-4740-41ae-b553-06efff48a68f.png)

**Comment by jodrell2000** [comment]
Both this, and the other similar issue #159 are due to me not being able to find a way to send a new line to the chat. From the discussions I've had in the dev chat on Discord it's not possible. There should be a wait function in there to ensure that the order is correct when sending multiple messages, but it's not perfect
